codecov:
  token: 216ba04a-be30-458f-b73d-4452dc4ed5c3
  max_report_age: off
  notify:
    require_ci_to_pass: yes

comment: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project: yes
      default:
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: yes
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

    # fixes:
    #   - "before/test-*::after/"
    #   - "before/::after/"  # move path   e.g., "before/path" => "after/path"
    #   - "::after/"         # move root   e.g., "path/" => "after/path/"
    #   - "before/::"        # reduce root e.g., "before/path/" => "path/"
